server:
  port: 8080

spring:
  application:
    name: board-project
  datasource:
    url: jdbc:mysql://localhost:4000/borad
    username: user1
    password: 1019
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: false

  sql:
    init:
      mode: always

---
spring:
  config:
    activate:
      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#  sql:
#    init:
#      mode always
#  test:
#    database:
#      replace: none




